on:
  push:
    branches:
      - main

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/orange723/91b39676071eec9d5b2cf8f2707b499e
          gist_title: whitelist.txt
          gist_description: Adguard VPN whitelist
          github_file: whitelist.txt